### PR TITLE
Added project title ;)

### PR DESCRIPTION
**Pull request by xh3n1**

### CODE REVIEW

**Review by LukasReschke — APPROVED** [review]

**Comment by rullzer** [comment]
Ah finally a title!

**Review by ChristophWurst — APPROVED** [review]
Tested and works

**Review by skjnldsv — APPROVED** [review]
:elephant:

**Comment by xh3n1** [comment]
@LukasReschke it’s been tested by the community, feel free to merge it now 😜

**Comment by LukasReschke** [comment]
I don’t trust @ChristophWurst ‘s reviews. They usually miss critical bugs.

**Review by LukasReschke — APPROVED** [review]
Oh. Saw @rullzer stomped this too. This one is good then. Dismiss Christoph!

**Pull request merged**
